### PR TITLE
Allow to specify source and dest file

### PR DESCRIPTION
**Pull request by JoniJnm**
* Allow not to specify sourceFile
* Allow to specify destFile
* Avoid duplicated new lines

### CODE REVIEW

**Comment by MirazMac** [comment]
Looks good, but may I ask what problem does this solve or which benefit it adds?

**Comment by JoniJnm** [comment]
In my use case I want to export the current ENV to a file, so there is not a sourceFile

(The real case: there are more than one source files, I need a file merging all of them)

**Comment by MirazMac** [comment]
Ok that seems like a valid use case. I'll merge this for now and publish a new release. Also I'm planning to rewrite it for PHP 8.0+ and release using semantic versioning so I'll keep this change in mind when rewriting it.

**Comment by JoniJnm** [comment]
Good.

I didn't want to change more the interface but I think the "force" argument should not exists in the write function. Sounds like it is a "overwrite". The hasChanges() function still exists so the clients can check it

In my use case, if I don't set any key=value, the parameter `changes` is false and by default the write function won't create the file

it's just a strange argument (in my opinion)

**Comment by MirazMac** [comment]
Originally I didn't plan to publish this I only made this to use internally so a lot of inconsistencies or strange choices can be seen.
I'll keep these in mind. Thanks for your suggestion.

**Pull request merged**
